//
// File generated by HDevelop for HALCON/.NET (C#) Version 20.11.0.0
// Non-ASCII strings in this file are encoded in local-8-bit encoding (cp936).
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//

using HalconDotNet;

public partial class HDevelopExport
{
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
  public HDevelopExport()
  {
    // Default settings used in HDevelop
    HOperatorSet.SetSystem("width", 512);
    HOperatorSet.SetSystem("height", 512);
    if (HalconAPI.isWindows)
      HOperatorSet.SetSystem("use_window_thread","true");
    action();
  }
#endif

  // Procedures 
  // External procedures 
  // Chapter: Graphics / Text
  // Short Description: This procedure writes one or multiple text messages. 
  public void disp_message (HTuple hv_WindowHandle, HTuple hv_String, HTuple hv_CoordSystem, 
      HTuple hv_Row, HTuple hv_Column, HTuple hv_Color, HTuple hv_Box)
  {



    // Local iconic variables 

    // Local control variables 

    HTuple hv_GenParamName = new HTuple(), hv_GenParamValue = new HTuple();
    HTuple   hv_Color_COPY_INP_TMP = new HTuple(hv_Color);
    HTuple   hv_Column_COPY_INP_TMP = new HTuple(hv_Column);
    HTuple   hv_CoordSystem_COPY_INP_TMP = new HTuple(hv_CoordSystem);
    HTuple   hv_Row_COPY_INP_TMP = new HTuple(hv_Row);

    // Initialize local and output iconic variables 
    try
    {
      //This procedure displays text in a graphics window.
      //
      //Input parameters:
      //WindowHandle: The WindowHandle of the graphics window, where
      //   the message should be displayed.
      //String: A tuple of strings containing the text messages to be displayed.
      //CoordSystem: If set to 'window', the text position is given
      //   with respect to the window coordinate system.
      //   If set to 'image', image coordinates are used.
      //   (This may be useful in zoomed images.)
      //Row: The row coordinate of the desired text position.
      //   You can pass a single value or a tuple of values.
      //   See the explanation below.
      //   Default: 12.
      //Column: The column coordinate of the desired text position.
      //   You can pass a single value or a tuple of values.
      //   See the explanation below.
      //   Default: 12.
      //Color: defines the color of the text as string.
      //   If set to [] or '' the currently set color is used.
      //   If a tuple of strings is passed, the colors are used cyclically
      //   for every text position defined by Row and Column,
      //   or every new text line in case of |Row| == |Column| == 1.
      //Box: A tuple controlling a possible box surrounding the text.
      //   Its entries:
      //   - Box[0]: Controls the box and its color. Possible values:
      //     -- 'true' (Default): An orange box is displayed.
      //     -- 'false': No box is displayed.
      //     -- color string: A box is displayed in the given color, e.g., 'white', '#FF00CC'.
      //   - Box[1] (Optional): Controls the shadow of the box. Possible values:
      //     -- 'true' (Default): A shadow is displayed in
      //               darker orange if Box[0] is not a color and in 'white' otherwise.
      //     -- 'false': No shadow is displayed.
      //     -- color string: A shadow is displayed in the given color, e.g., 'white', '#FF00CC'.
      //
      //It is possible to display multiple text strings in a single call.
      //In this case, some restrictions apply on the
      //parameters String, Row, and Column:
      //They can only have either 1 entry or n entries.
      //Behavior in the different cases:
      //   - Multiple text positions are specified, i.e.,
      //       - |Row| == n, |Column| == n
      //       - |Row| == n, |Column| == 1
      //       - |Row| == 1, |Column| == n
      //     In this case we distinguish:
      //       - |String| == n: Each element of String is displayed
      //                        at the corresponding position.
      //       - |String| == 1: String is displayed n times
      //                        at the corresponding positions.
      //   - Exactly one text position is specified,
      //      i.e., |Row| == |Column| == 1:
      //      Each element of String is display in a new textline.
      //
      //
      //Convert the parameters for disp_text.
      if ((int)((new HTuple(hv_Row_COPY_INP_TMP.TupleEqual(new HTuple()))).TupleOr(
          new HTuple(hv_Column_COPY_INP_TMP.TupleEqual(new HTuple())))) != 0)
      {

        hv_Color_COPY_INP_TMP.Dispose();
        hv_Column_COPY_INP_TMP.Dispose();
        hv_CoordSystem_COPY_INP_TMP.Dispose();
        hv_Row_COPY_INP_TMP.Dispose();
        hv_GenParamName.Dispose();
        hv_GenParamValue.Dispose();

        return;
      }
      if ((int)(new HTuple(hv_Row_COPY_INP_TMP.TupleEqual(-1))) != 0)
      {
        hv_Row_COPY_INP_TMP.Dispose();
        hv_Row_COPY_INP_TMP = 12;
      }
      if ((int)(new HTuple(hv_Column_COPY_INP_TMP.TupleEqual(-1))) != 0)
      {
        hv_Column_COPY_INP_TMP.Dispose();
        hv_Column_COPY_INP_TMP = 12;
      }
      //
      //Convert the parameter Box to generic parameters.
      hv_GenParamName.Dispose();
      hv_GenParamName = new HTuple();
      hv_GenParamValue.Dispose();
      hv_GenParamValue = new HTuple();
      if ((int)(new HTuple((new HTuple(hv_Box.TupleLength())).TupleGreater(0))) != 0)
      {
        if ((int)(new HTuple(((hv_Box.TupleSelect(0))).TupleEqual("false"))) != 0)
        {
          //Display no box
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
              "box");
          hv_GenParamName.Dispose();
          hv_GenParamName = ExpTmpLocalVar_GenParamName;
          }
          }
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
              "false");
          hv_GenParamValue.Dispose();
          hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
          }
          }
        }
        else if ((int)(new HTuple(((hv_Box.TupleSelect(0))).TupleNotEqual(
            "true"))) != 0)
        {
          //Set a color other than the default.
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
              "box_color");
          hv_GenParamName.Dispose();
          hv_GenParamName = ExpTmpLocalVar_GenParamName;
          }
          }
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
              hv_Box.TupleSelect(0));
          hv_GenParamValue.Dispose();
          hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
          }
          }
        }
      }
      if ((int)(new HTuple((new HTuple(hv_Box.TupleLength())).TupleGreater(1))) != 0)
      {
        if ((int)(new HTuple(((hv_Box.TupleSelect(1))).TupleEqual("false"))) != 0)
        {
          //Display no shadow.
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
              "shadow");
          hv_GenParamName.Dispose();
          hv_GenParamName = ExpTmpLocalVar_GenParamName;
          }
          }
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
              "false");
          hv_GenParamValue.Dispose();
          hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
          }
          }
        }
        else if ((int)(new HTuple(((hv_Box.TupleSelect(1))).TupleNotEqual(
            "true"))) != 0)
        {
          //Set a shadow color other than the default.
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
              "shadow_color");
          hv_GenParamName.Dispose();
          hv_GenParamName = ExpTmpLocalVar_GenParamName;
          }
          }
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
              hv_Box.TupleSelect(1));
          hv_GenParamValue.Dispose();
          hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
          }
          }
        }
      }
      //Restore default CoordSystem behavior.
      if ((int)(new HTuple(hv_CoordSystem_COPY_INP_TMP.TupleNotEqual("window"))) != 0)
      {
        hv_CoordSystem_COPY_INP_TMP.Dispose();
        hv_CoordSystem_COPY_INP_TMP = "image";
      }
      //
      if ((int)(new HTuple(hv_Color_COPY_INP_TMP.TupleEqual(""))) != 0)
      {
        //disp_text does not accept an empty string for Color.
        hv_Color_COPY_INP_TMP.Dispose();
        hv_Color_COPY_INP_TMP = new HTuple();
      }
      //
      HOperatorSet.DispText(hv_WindowHandle, hv_String, hv_CoordSystem_COPY_INP_TMP, 
          hv_Row_COPY_INP_TMP, hv_Column_COPY_INP_TMP, hv_Color_COPY_INP_TMP, hv_GenParamName, 
          hv_GenParamValue);

      hv_Color_COPY_INP_TMP.Dispose();
      hv_Column_COPY_INP_TMP.Dispose();
      hv_CoordSystem_COPY_INP_TMP.Dispose();
      hv_Row_COPY_INP_TMP.Dispose();
      hv_GenParamName.Dispose();
      hv_GenParamValue.Dispose();

      return;
    }
    catch (HalconException HDevExpDefaultException)
    {

      hv_Color_COPY_INP_TMP.Dispose();
      hv_Column_COPY_INP_TMP.Dispose();
      hv_CoordSystem_COPY_INP_TMP.Dispose();
      hv_Row_COPY_INP_TMP.Dispose();
      hv_GenParamName.Dispose();
      hv_GenParamValue.Dispose();

      throw HDevExpDefaultException;
    }
  }

  // Chapter: Graphics / Text
  // Short Description: Set font independent of OS 
  public void set_display_font (HTuple hv_WindowHandle, HTuple hv_Size, HTuple hv_Font, 
      HTuple hv_Bold, HTuple hv_Slant)
  {



    // Local iconic variables 

    // Local control variables 

    HTuple hv_OS = new HTuple(), hv_Fonts = new HTuple();
    HTuple hv_Style = new HTuple(), hv_Exception = new HTuple();
    HTuple hv_AvailableFonts = new HTuple(), hv_Fdx = new HTuple();
    HTuple hv_Indices = new HTuple();
    HTuple   hv_Font_COPY_INP_TMP = new HTuple(hv_Font);
    HTuple   hv_Size_COPY_INP_TMP = new HTuple(hv_Size);

    // Initialize local and output iconic variables 
    try
    {
      //This procedure sets the text font of the current window with
      //the specified attributes.
      //
      //Input parameters:
      //WindowHandle: The graphics window for which the font will be set
      //Size: The font size. If Size=-1, the default of 16 is used.
      //Bold: If set to 'true', a bold font is used
      //Slant: If set to 'true', a slanted font is used
      //
      hv_OS.Dispose();
      HOperatorSet.GetSystem("operating_system", out hv_OS);
      if ((int)((new HTuple(hv_Size_COPY_INP_TMP.TupleEqual(new HTuple()))).TupleOr(
          new HTuple(hv_Size_COPY_INP_TMP.TupleEqual(-1)))) != 0)
      {
        hv_Size_COPY_INP_TMP.Dispose();
        hv_Size_COPY_INP_TMP = 16;
      }
      if ((int)(new HTuple(((hv_OS.TupleSubstr(0,2))).TupleEqual("Win"))) != 0)
      {
        //Restore previous behaviour
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        {
        HTuple 
          ExpTmpLocalVar_Size = ((1.13677*hv_Size_COPY_INP_TMP)).TupleInt()
            ;
        hv_Size_COPY_INP_TMP.Dispose();
        hv_Size_COPY_INP_TMP = ExpTmpLocalVar_Size;
        }
        }
      }
      else
      {
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        {
        HTuple 
          ExpTmpLocalVar_Size = hv_Size_COPY_INP_TMP.TupleInt()
            ;
        hv_Size_COPY_INP_TMP.Dispose();
        hv_Size_COPY_INP_TMP = ExpTmpLocalVar_Size;
        }
        }
      }
      if ((int)(new HTuple(hv_Font_COPY_INP_TMP.TupleEqual("Courier"))) != 0)
      {
        hv_Fonts.Dispose();
        hv_Fonts = new HTuple();
        hv_Fonts[0] = "Courier";
        hv_Fonts[1] = "Courier 10 Pitch";
        hv_Fonts[2] = "Courier New";
        hv_Fonts[3] = "CourierNew";
        hv_Fonts[4] = "Liberation Mono";
      }
      else if ((int)(new HTuple(hv_Font_COPY_INP_TMP.TupleEqual("mono"))) != 0)
      {
        hv_Fonts.Dispose();
        hv_Fonts = new HTuple();
        hv_Fonts[0] = "Consolas";
        hv_Fonts[1] = "Menlo";
        hv_Fonts[2] = "Courier";
        hv_Fonts[3] = "Courier 10 Pitch";
        hv_Fonts[4] = "FreeMono";
        hv_Fonts[5] = "Liberation Mono";
      }
      else if ((int)(new HTuple(hv_Font_COPY_INP_TMP.TupleEqual("sans"))) != 0)
      {
        hv_Fonts.Dispose();
        hv_Fonts = new HTuple();
        hv_Fonts[0] = "Luxi Sans";
        hv_Fonts[1] = "DejaVu Sans";
        hv_Fonts[2] = "FreeSans";
        hv_Fonts[3] = "Arial";
        hv_Fonts[4] = "Liberation Sans";
      }
      else if ((int)(new HTuple(hv_Font_COPY_INP_TMP.TupleEqual("serif"))) != 0)
      {
        hv_Fonts.Dispose();
        hv_Fonts = new HTuple();
        hv_Fonts[0] = "Times New Roman";
        hv_Fonts[1] = "Luxi Serif";
        hv_Fonts[2] = "DejaVu Serif";
        hv_Fonts[3] = "FreeSerif";
        hv_Fonts[4] = "Utopia";
        hv_Fonts[5] = "Liberation Serif";
      }
      else
      {
        hv_Fonts.Dispose();
        hv_Fonts = new HTuple(hv_Font_COPY_INP_TMP);
      }
      hv_Style.Dispose();
      hv_Style = "";
      if ((int)(new HTuple(hv_Bold.TupleEqual("true"))) != 0)
      {
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        {
        HTuple 
          ExpTmpLocalVar_Style = hv_Style+"Bold";
        hv_Style.Dispose();
        hv_Style = ExpTmpLocalVar_Style;
        }
        }
      }
      else if ((int)(new HTuple(hv_Bold.TupleNotEqual("false"))) != 0)
      {
        hv_Exception.Dispose();
        hv_Exception = "Wrong value of control parameter Bold";
        throw new HalconException(hv_Exception);
      }
      if ((int)(new HTuple(hv_Slant.TupleEqual("true"))) != 0)
      {
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        {
        HTuple 
          ExpTmpLocalVar_Style = hv_Style+"Italic";
        hv_Style.Dispose();
        hv_Style = ExpTmpLocalVar_Style;
        }
        }
      }
      else if ((int)(new HTuple(hv_Slant.TupleNotEqual("false"))) != 0)
      {
        hv_Exception.Dispose();
        hv_Exception = "Wrong value of control parameter Slant";
        throw new HalconException(hv_Exception);
      }
      if ((int)(new HTuple(hv_Style.TupleEqual(""))) != 0)
      {
        hv_Style.Dispose();
        hv_Style = "Normal";
      }
      hv_AvailableFonts.Dispose();
      HOperatorSet.QueryFont(hv_WindowHandle, out hv_AvailableFonts);
      hv_Font_COPY_INP_TMP.Dispose();
      hv_Font_COPY_INP_TMP = "";
      for (hv_Fdx=0; (int)hv_Fdx<=(int)((new HTuple(hv_Fonts.TupleLength()))-1); hv_Fdx = (int)hv_Fdx + 1)
      {
        hv_Indices.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_Indices = hv_AvailableFonts.TupleFind(
            hv_Fonts.TupleSelect(hv_Fdx));
        }
        if ((int)(new HTuple((new HTuple(hv_Indices.TupleLength())).TupleGreater(
            0))) != 0)
        {
          if ((int)(new HTuple(((hv_Indices.TupleSelect(0))).TupleGreaterEqual(0))) != 0)
          {
            hv_Font_COPY_INP_TMP.Dispose();
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
            hv_Font_COPY_INP_TMP = hv_Fonts.TupleSelect(
                hv_Fdx);
            }
            break;
          }
        }
      }
      if ((int)(new HTuple(hv_Font_COPY_INP_TMP.TupleEqual(""))) != 0)
      {
        throw new HalconException("Wrong value of control parameter Font");
      }
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      {
      HTuple 
        ExpTmpLocalVar_Font = (((hv_Font_COPY_INP_TMP+"-")+hv_Style)+"-")+hv_Size_COPY_INP_TMP;
      hv_Font_COPY_INP_TMP.Dispose();
      hv_Font_COPY_INP_TMP = ExpTmpLocalVar_Font;
      }
      }
      HOperatorSet.SetFont(hv_WindowHandle, hv_Font_COPY_INP_TMP);

      hv_Font_COPY_INP_TMP.Dispose();
      hv_Size_COPY_INP_TMP.Dispose();
      hv_OS.Dispose();
      hv_Fonts.Dispose();
      hv_Style.Dispose();
      hv_Exception.Dispose();
      hv_AvailableFonts.Dispose();
      hv_Fdx.Dispose();
      hv_Indices.Dispose();

      return;
    }
    catch (HalconException HDevExpDefaultException)
    {

      hv_Font_COPY_INP_TMP.Dispose();
      hv_Size_COPY_INP_TMP.Dispose();
      hv_OS.Dispose();
      hv_Fonts.Dispose();
      hv_Style.Dispose();
      hv_Exception.Dispose();
      hv_AvailableFonts.Dispose();
      hv_Fdx.Dispose();
      hv_Indices.Dispose();

      throw HDevExpDefaultException;
    }
  }

  // Local procedures 
  public void CreateShapeModel (HObject ho_Image, HObject ho_ModelRegion, out HObject ho_ModelContours, 
      HTuple hv_DictHandle, out HTuple hv_ModelID, out HTuple hv_NccModelID, out HTuple hv_Exception)
  {




    // Local iconic variables 

    HObject ho_TemplateImage=null, ho_Rectangle=null;
    HObject ho_ImageReduced=null;

    // Local control variables 

    HTuple hv_NumLevels = new HTuple(), hv_AngleStart = new HTuple();
    HTuple hv_AngleExtent = new HTuple(), hv_AngleStep = new HTuple();
    HTuple hv_IsEnableNcc = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_ModelContours);
    HOperatorSet.GenEmptyObj(out ho_TemplateImage);
    HOperatorSet.GenEmptyObj(out ho_Rectangle);
    HOperatorSet.GenEmptyObj(out ho_ImageReduced);
    hv_ModelID = new HTuple();
    hv_NccModelID = new HTuple();
    hv_Exception = new HTuple();
    try
    {
      try
      {
        hv_NumLevels.Dispose();
        HOperatorSet.GetDictTuple(hv_DictHandle, "NumLevels", out hv_NumLevels);
        hv_AngleStart.Dispose();
        HOperatorSet.GetDictTuple(hv_DictHandle, "AngleStart", out hv_AngleStart);
        hv_AngleExtent.Dispose();
        HOperatorSet.GetDictTuple(hv_DictHandle, "AngleExtent", out hv_AngleExtent);
        hv_AngleStep.Dispose();
        HOperatorSet.GetDictTuple(hv_DictHandle, "AngleStep", out hv_AngleStep);
        hv_IsEnableNcc.Dispose();
        HOperatorSet.GetDictTuple(hv_DictHandle, "EnableNcc", out hv_IsEnableNcc);
        //get_dict_tuple (DictHandle, 'MinContrast', MinContrast)
        //get_dict_tuple (DictHandle, 'MaxContrast', MaxContrast)
        //get_dict_tuple (DictHandle, 'MinComponentLength', MinComponentLength)
        ho_TemplateImage.Dispose();
        HOperatorSet.ReduceDomain(ho_Image, ho_ModelRegion, out ho_TemplateImage);
        //create_shape_model (TemplateImage, NumLevels, rad(AngleStart), rad(AngleExtent), rad(AngleStep), 'auto', 'use_polarity', [MinContrast,MaxContrast,MinComponentLength], 20, ModelID)
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_ModelID.Dispose();
        HOperatorSet.CreateShapeModel(ho_TemplateImage, "auto", hv_AngleStart.TupleRad()
            , hv_AngleExtent.TupleRad(), "auto", "auto", "use_polarity", "auto", 
            "auto", out hv_ModelID);
        }
        if ((int)(hv_IsEnableNcc) != 0)
        {

          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          hv_NccModelID.Dispose();
          HOperatorSet.CreateNccModel(ho_TemplateImage, "auto", hv_AngleStart.TupleRad()
              , hv_AngleExtent.TupleRad(), "auto", "use_polarity", out hv_NccModelID);
          }
        }
        else
        {
          ho_Rectangle.Dispose();
          HOperatorSet.GenRectangle1(out ho_Rectangle, 1, 1, 100, 100);
          ho_ImageReduced.Dispose();
          HOperatorSet.ReduceDomain(ho_Image, ho_Rectangle, out ho_ImageReduced);
          hv_NccModelID.Dispose();
          HOperatorSet.CreateNccModel(ho_ImageReduced, "auto", -0.39, 0.79, "auto", 
              "use_polarity", out hv_NccModelID);
        }
        ho_ModelContours.Dispose();
        HOperatorSet.GetShapeModelContours(out ho_ModelContours, hv_ModelID, 1);

      }
      // catch (Exception) 
      catch (HalconException HDevExpDefaultException1)
      {
        HDevExpDefaultException1.ToHTuple(out hv_Exception);
      }
      ho_TemplateImage.Dispose();
      ho_Rectangle.Dispose();
      ho_ImageReduced.Dispose();

      hv_NumLevels.Dispose();
      hv_AngleStart.Dispose();
      hv_AngleExtent.Dispose();
      hv_AngleStep.Dispose();
      hv_IsEnableNcc.Dispose();

      return;
    }
    catch (HalconException HDevExpDefaultException)
    {
      ho_TemplateImage.Dispose();
      ho_Rectangle.Dispose();
      ho_ImageReduced.Dispose();

      hv_NumLevels.Dispose();
      hv_AngleStart.Dispose();
      hv_AngleExtent.Dispose();
      hv_AngleStep.Dispose();
      hv_IsEnableNcc.Dispose();

      throw HDevExpDefaultException;
    }
  }

  public void FindShapeModel (HObject ho_Image, HObject ho_ROI_1_0, out HObject ho_ConcatContour, 
      HTuple hv_DictHandle, HTuple hv_ModelID, HTuple hv_NccModelID, out HTuple hv_OutputTuple, 
      out HTuple hv_Exception)
  {




    // Stack for temporary objects 
    HObject[] OTemp = new HObject[20];

    // Local iconic variables 

    HObject ho_ImageReduced=null, ho_ModelContours1=null;
    HObject ho_ContoursAffineTrans=null;

    // Local control variables 

    HTuple hv_AngleStart = new HTuple(), hv_AngleExtent = new HTuple();
    HTuple hv_MinScore = new HTuple(), hv_NumMatches = new HTuple();
    HTuple hv_MaxOverLap = new HTuple(), hv_NumLevels = new HTuple();
    HTuple hv_IsEnableNcc = new HTuple(), hv_Row = new HTuple();
    HTuple hv_Column = new HTuple(), hv_Angle = new HTuple();
    HTuple hv_Score = new HTuple(), hv_Index = new HTuple();
    HTuple hv_HomMat2D = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_ConcatContour);
    HOperatorSet.GenEmptyObj(out ho_ImageReduced);
    HOperatorSet.GenEmptyObj(out ho_ModelContours1);
    HOperatorSet.GenEmptyObj(out ho_ContoursAffineTrans);
    hv_OutputTuple = new HTuple();
    hv_Exception = new HTuple();
    try
    {
      try
      {
        hv_AngleStart.Dispose();
        HOperatorSet.GetDictTuple(hv_DictHandle, "AngleStart", out hv_AngleStart);
        hv_AngleExtent.Dispose();
        HOperatorSet.GetDictTuple(hv_DictHandle, "AngleExtent", out hv_AngleExtent);
        hv_MinScore.Dispose();
        HOperatorSet.GetDictTuple(hv_DictHandle, "MinScore", out hv_MinScore);
        hv_NumMatches.Dispose();
        HOperatorSet.GetDictTuple(hv_DictHandle, "NumMatches", out hv_NumMatches);
        hv_MaxOverLap.Dispose();
        HOperatorSet.GetDictTuple(hv_DictHandle, "MaxOverLap", out hv_MaxOverLap);
        hv_NumLevels.Dispose();
        HOperatorSet.GetDictTuple(hv_DictHandle, "NumLevels", out hv_NumLevels);
        hv_IsEnableNcc.Dispose();
        HOperatorSet.GetDictTuple(hv_DictHandle, "EnableNcc", out hv_IsEnableNcc);
        ho_ImageReduced.Dispose();
        HOperatorSet.ReduceDomain(ho_Image, ho_ROI_1_0, out ho_ImageReduced);
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_Row.Dispose();hv_Column.Dispose();hv_Angle.Dispose();hv_Score.Dispose();
        HOperatorSet.FindShapeModel(ho_ImageReduced, hv_ModelID, hv_AngleStart.TupleRad()
            , hv_AngleExtent.TupleRad(), hv_MinScore, hv_NumMatches, hv_MaxOverLap, 
            "least_squares", hv_NumLevels.TupleConcat(1), 0.9, out hv_Row, out hv_Column, 
            out hv_Angle, out hv_Score);
        }
        if ((int)((new HTuple((new HTuple(hv_Row.TupleLength())).TupleEqual(0))).TupleAnd(
            hv_IsEnableNcc)) != 0)
        {
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          hv_Row.Dispose();hv_Column.Dispose();hv_Angle.Dispose();hv_Score.Dispose();
          HOperatorSet.FindNccModel(ho_ImageReduced, hv_NccModelID, hv_AngleStart.TupleRad()
              , hv_AngleExtent.TupleRad(), hv_MinScore, hv_NumMatches, hv_MaxOverLap, 
              "true", hv_NumLevels.TupleConcat(1), out hv_Row, out hv_Column, out hv_Angle, 
              out hv_Score);
          }
        }

        hv_OutputTuple.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_OutputTuple = new HTuple();
        hv_OutputTuple = hv_OutputTuple.TupleConcat(hv_Row, hv_Column, hv_Angle, hv_Score);
        }
        ho_ModelContours1.Dispose();
        HOperatorSet.GetShapeModelContours(out ho_ModelContours1, hv_ModelID, 1);
        ho_ConcatContour.Dispose();
        HOperatorSet.GenEmptyObj(out ho_ConcatContour);
        for (hv_Index=0; (int)hv_Index<=(int)((new HTuple(hv_Row.TupleLength()))-1); hv_Index = (int)hv_Index + 1)
        {
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          hv_HomMat2D.Dispose();
          HOperatorSet.VectorAngleToRigid(0, 0, 0, hv_Row.TupleSelect(hv_Index), 
              hv_Column.TupleSelect(hv_Index), hv_Angle.TupleSelect(hv_Index), out hv_HomMat2D);
          }
          ho_ContoursAffineTrans.Dispose();
          HOperatorSet.AffineTransContourXld(ho_ModelContours1, out ho_ContoursAffineTrans, 
              hv_HomMat2D);
          {
          HObject ExpTmpOutVar_0;
          HOperatorSet.ConcatObj(ho_ConcatContour, ho_ContoursAffineTrans, out ExpTmpOutVar_0
              );
          ho_ConcatContour.Dispose();
          ho_ConcatContour = ExpTmpOutVar_0;
          }
        }
      }
      // catch (Exception) 
      catch (HalconException HDevExpDefaultException1)
      {
        HDevExpDefaultException1.ToHTuple(out hv_Exception);
      }

      ho_ImageReduced.Dispose();
      ho_ModelContours1.Dispose();
      ho_ContoursAffineTrans.Dispose();

      hv_AngleStart.Dispose();
      hv_AngleExtent.Dispose();
      hv_MinScore.Dispose();
      hv_NumMatches.Dispose();
      hv_MaxOverLap.Dispose();
      hv_NumLevels.Dispose();
      hv_IsEnableNcc.Dispose();
      hv_Row.Dispose();
      hv_Column.Dispose();
      hv_Angle.Dispose();
      hv_Score.Dispose();
      hv_Index.Dispose();
      hv_HomMat2D.Dispose();

      return;
    }
    catch (HalconException HDevExpDefaultException)
    {
      ho_ImageReduced.Dispose();
      ho_ModelContours1.Dispose();
      ho_ContoursAffineTrans.Dispose();

      hv_AngleStart.Dispose();
      hv_AngleExtent.Dispose();
      hv_MinScore.Dispose();
      hv_NumMatches.Dispose();
      hv_MaxOverLap.Dispose();
      hv_NumLevels.Dispose();
      hv_IsEnableNcc.Dispose();
      hv_Row.Dispose();
      hv_Column.Dispose();
      hv_Angle.Dispose();
      hv_Score.Dispose();
      hv_Index.Dispose();
      hv_HomMat2D.Dispose();

      throw HDevExpDefaultException;
    }
  }

#if !NO_EXPORT_MAIN
  // Main procedure 
  private void action()
  {


    // Local iconic variables 

    HObject ho_Image, ho_ModelRegion, ho_ModelContours;
    HObject ho_Image2617221443, ho_ROI_1, ho_ConcatContour;

    // Local control variables 

    HTuple hv_DictHandle = new HTuple(), hv_ModelID = new HTuple();
    HTuple hv_NccModelID = new HTuple(), hv_Exception = new HTuple();
    HTuple hv_WindowHandle1 = new HTuple(), hv_Row1 = new HTuple();
    HTuple hv_Column1 = new HTuple(), hv_Row2 = new HTuple();
    HTuple hv_Column2 = new HTuple(), hv_OutputDictHandle = new HTuple();
    HTuple hv_Exception1 = new HTuple(), hv_ang = new HTuple();
    HTuple hv_WindowHandle = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Image);
    HOperatorSet.GenEmptyObj(out ho_ModelRegion);
    HOperatorSet.GenEmptyObj(out ho_ModelContours);
    HOperatorSet.GenEmptyObj(out ho_Image2617221443);
    HOperatorSet.GenEmptyObj(out ho_ROI_1);
    HOperatorSet.GenEmptyObj(out ho_ConcatContour);
    try
    {
      ho_Image.Dispose();
      HOperatorSet.ReadImage(out ho_Image, "D:/Ì¼½¬Òø½¬/OC½ºÐ§¹ûÍ¼/AG/20220615_1/1_1_17104862.tiff");

      hv_DictHandle.Dispose();
      HOperatorSet.CreateDict(out hv_DictHandle);
      HOperatorSet.SetDictTuple(hv_DictHandle, "NumLevels", 4);
      HOperatorSet.SetDictTuple(hv_DictHandle, "AngleStart", 0);
      HOperatorSet.SetDictTuple(hv_DictHandle, "AngleExtent", 360);
      HOperatorSet.SetDictTuple(hv_DictHandle, "AngleStep", 89);
      //set_dict_tuple (DictHandle, 'MinContrast', 79)
      //set_dict_tuple (DictHandle, 'MaxContrast', 146)
      //set_dict_tuple (DictHandle, 'MinComponentLength', 58)
      HOperatorSet.SetDictTuple(hv_DictHandle, "MinScore", 0.5);
      HOperatorSet.SetDictTuple(hv_DictHandle, "NumMatches", 1);
      HOperatorSet.SetDictTuple(hv_DictHandle, "MaxOverLap", 0.5);
      HOperatorSet.SetDictTuple(hv_DictHandle, "IsEnableNcc", 0);

      ho_ModelRegion.Dispose();
      HOperatorSet.GenCircle(out ho_ModelRegion, 111, 487, 100);

      ho_ModelContours.Dispose();hv_ModelID.Dispose();hv_NccModelID.Dispose();hv_Exception.Dispose();
      CreateShapeModel(ho_Image, ho_ModelRegion, out ho_ModelContours, hv_DictHandle, 
          out hv_ModelID, out hv_NccModelID, out hv_Exception);


      ho_Image2617221443.Dispose();
      HOperatorSet.ReadImage(out ho_Image2617221443, "D:/Ì¼½¬Òø½¬/OC½ºÐ§¹ûÍ¼/AG/20220615_1/2_6_17221443.tiff");

      if (HDevWindowStack.IsOpen())
      {
        hv_WindowHandle1 = HDevWindowStack.GetActive();
      }
      hv_Row1.Dispose();hv_Column1.Dispose();hv_Row2.Dispose();hv_Column2.Dispose();
      HOperatorSet.DrawRectangle1(hv_WindowHandle1, out hv_Row1, out hv_Column1, 
          out hv_Row2, out hv_Column2);
      ho_ROI_1.Dispose();
      HOperatorSet.GenRectangle1(out ho_ROI_1, hv_Row1, hv_Column1, hv_Row2, hv_Column2);


      ho_ConcatContour.Dispose();hv_OutputDictHandle.Dispose();hv_Exception1.Dispose();
      FindShapeModel(ho_Image2617221443, ho_ROI_1, out ho_ConcatContour, hv_DictHandle, 
          hv_ModelID, hv_NccModelID, out hv_OutputDictHandle, out hv_Exception1);
      hv_ang.Dispose();
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_ang = ((hv_OutputDictHandle.TupleSelect(
          2))).TupleDeg();
      }


      if (HDevWindowStack.IsOpen())
      {
        hv_WindowHandle = HDevWindowStack.GetActive();
      }
      set_display_font(hv_WindowHandle, 16, "mono", "true", "false");
      disp_message(hv_WindowHandle, hv_OutputDictHandle, "window", 12, 12, "black", 
          "true");
    }
    catch (HalconException HDevExpDefaultException)
    {
      ho_Image.Dispose();
      ho_ModelRegion.Dispose();
      ho_ModelContours.Dispose();
      ho_Image2617221443.Dispose();
      ho_ROI_1.Dispose();
      ho_ConcatContour.Dispose();

      hv_DictHandle.Dispose();
      hv_ModelID.Dispose();
      hv_NccModelID.Dispose();
      hv_Exception.Dispose();
      hv_WindowHandle1.Dispose();
      hv_Row1.Dispose();
      hv_Column1.Dispose();
      hv_Row2.Dispose();
      hv_Column2.Dispose();
      hv_OutputDictHandle.Dispose();
      hv_Exception1.Dispose();
      hv_ang.Dispose();
      hv_WindowHandle.Dispose();

      throw HDevExpDefaultException;
    }
    ho_Image.Dispose();
    ho_ModelRegion.Dispose();
    ho_ModelContours.Dispose();
    ho_Image2617221443.Dispose();
    ho_ROI_1.Dispose();
    ho_ConcatContour.Dispose();

    hv_DictHandle.Dispose();
    hv_ModelID.Dispose();
    hv_NccModelID.Dispose();
    hv_Exception.Dispose();
    hv_WindowHandle1.Dispose();
    hv_Row1.Dispose();
    hv_Column1.Dispose();
    hv_Row2.Dispose();
    hv_Column2.Dispose();
    hv_OutputDictHandle.Dispose();
    hv_Exception1.Dispose();
    hv_ang.Dispose();
    hv_WindowHandle.Dispose();

  }

#endif


}
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
public class HDevelopExportApp
{
  static void Main(string[] args)
  {
    new HDevelopExport();
  }
}
#endif

